package skills

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// ── Skill ────────────────────────────────────────────────────────────────────

// Skill represents a loaded skill. It is either a markdown skill (Prompt != "")
// or a YAML pipeline skill (Pipeline != nil). Both appear identically in the
// router catalog and respond to /skill-name commands.
type Skill struct {
	Name          string         `yaml:"name"`
	Version       string         `yaml:"version"`
	Description   string         `yaml:"description"`
	RequiredTools []string       `yaml:"required_tools"`
	// Tier selects the LLM model tier used when this skill is active.
	// Valid values: "base", "medium", "strong".
	// Legacy values accepted: "direct"→base, "atomic"→medium, "workflow"/"complex"→strong.
	Tier           string         `yaml:"tier"`
	LegacyTier     string         `yaml:"complexity"` // backward compat — merged into Tier on load
	// AutoGenerated marks skills created by the Planner (not hand-written).
	// Only auto-generated skills are subject to Evaluator quality checks.
	AutoGenerated bool           `yaml:"auto_generated,omitempty"`
	// SuccessCount tracks consecutive evaluator-pass runs for auto-generated skills.
	// When it reaches the configured threshold, evaluation stops.
	SuccessCount  int            `yaml:"success_count,omitempty"`
	Prompt        string         `yaml:"-"` // markdown body (regular skills)
	FilePath      string         `yaml:"-"`
	Pipeline      *PipelineSkill `yaml:"-"` // non-nil for pipeline skills
}

// IsPipeline reports whether this skill is a YAML pipeline skill.
func (s *Skill) IsPipeline() bool { return s.Pipeline != nil }

// CommandName returns the slash-command form: lowercase, spaces/underscores → hyphens.
// e.g. "Code Review" → "code-review", "deep_research" → "deep-research"
func (s *Skill) CommandName() string {
	n := strings.ToLower(s.Name)
	n = strings.ReplaceAll(n, " ", "-")
	n = strings.ReplaceAll(n, "_", "-")
	return n
}

// ── Pipeline types ────────────────────────────────────────────────────────────

// PipelineSkill is the parsed content of a .yaml pipeline skill file.
type PipelineSkill struct {
	// Vars declares pipeline variables and their default values.
	// $vars.input is always populated from the user's message.
	// Returns names the pipeline variable whose value is shown to the user.
	// When empty, the engine tries "result", "output", then "answer".
	Returns  string                 `yaml:"returns"`
	Vars     map[string]interface{} `yaml:"vars"`
	Pipeline []PipelineNode         `yaml:"pipeline"`
}

// OutputsMap is the type for a node's outputs declaration.
// It supports three YAML forms for convenience:
//
//   - map:    outputs: {my_var: result, count: total}
//             Each pipeline var reads the named key from node_complete vars.
//   - list:   outputs: [summary, title]
//             Each pipeline var reads the key with the SAME name (summary→summary, title→title).
//   - scalar: outputs: my_var
//             Single pipeline var reads the canonical "result" key from node_complete.
type OutputsMap map[string]string

// UnmarshalYAML implements yaml.Unmarshaler to accept map, sequence, and scalar.
func (o *OutputsMap) UnmarshalYAML(value *yaml.Node) error {
	switch value.Kind {
	case yaml.MappingNode:
		var m map[string]string
		if err := value.Decode(&m); err != nil {
			return err
		}
		*o = m
	case yaml.SequenceNode:
		var keys []string
		if err := value.Decode(&keys); err != nil {
			return err
		}
		m := make(OutputsMap, len(keys))
		for _, k := range keys {
			m[k] = k // each var reads the node_complete key with the same name
		}
		*o = m
	case yaml.ScalarNode:
		if value.Value != "" {
			*o = OutputsMap{value.Value: "result"} // single var reads canonical "result" key
		}
	default:
		return fmt.Errorf("outputs: expected map, sequence, or string")
	}
	return nil
}

// PipelineNode is one step in a pipeline.
type PipelineNode struct {
	// ID is the unique node identifier used for variable namespacing and todo display.
	ID string `yaml:"id"`

	// Type is "agent" (LLM-driven, default) or "auto" (direct tool call, no LLM).
	Type string `yaml:"type"`

	// ── auto-only ─────────────────────────────────────────────────────────────

	// Tool is the tool to call for type=auto nodes.
	Tool string `yaml:"tool"`

	// ── agent-only ────────────────────────────────────────────────────────────

	// Skill optionally activates a regular or pipeline skill inside this node.
	// Pipeline skills may be nested at most 1 level deep.
	Skill string `yaml:"skill"`

	// Tools is the tool allowlist for the node's agent.
	// If empty and no skill is specified, the node has access to all global tools.
	Tools []string `yaml:"tools"`

	// Tier selects the LLM model: "base", "medium", or "strong".
	// The engine automatically falls back one tier on transient LLM errors.
	// Legacy values "direct"/"atomic"/"workflow" are accepted and normalised.
	Tier           string `yaml:"tier"`
	LegacyTier     string `yaml:"complexity"` // backward compat

	// Prompt is the task description for the node's agent.
	// Supports: {{name}} or {{$vars.name}}, {{$foreach.current}}, {{$foreach.index}}.
	Prompt string `yaml:"prompt"`

	// ── both ──────────────────────────────────────────────────────────────────

	// Foreach specifies a pipeline variable (bare name or $vars.name) to iterate over.
	// $foreach.current and $foreach.index are available inside the node.
	// Output variables are collected as arrays after all iterations complete.
	Foreach string `yaml:"foreach"`

	// Inputs maps tool/agent argument names to values.
	// String values starting with $ are variable references: $name (shorthand for
	// $vars.name), $foreach.current, $foreach.current.field, $foreach.index.
	// Non-string values pass through unchanged; nested strings are resolved recursively.
	Inputs map[string]interface{} `yaml:"inputs"`

	// Outputs maps pipeline variable names to the node's output keys.
	// Accepts map ({var: key}), list ([var1, var2] → all read "result"), or scalar ("var").
	Outputs OutputsMap `yaml:"outputs"`

	// Validate specifies requirements for the node's inputs.
	// Currently supported: "not_empty" (fails pipeline if any resolved input is empty).
	Validate string `yaml:"validate"`
}

// ── Loaders ───────────────────────────────────────────────────────────────────

// LoadSkills scans dir for .md (regular) and .yaml (pipeline) skill files.
func LoadSkills(dir string) ([]Skill, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to read skills directory: %w", err)
	}

	var loaded []Skill
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		path := filepath.Join(dir, name)

		var skill *Skill
		var parseErr error

		switch {
		case strings.HasSuffix(name, ".md"):
			skill, parseErr = parseSkillFile(path)
		case strings.HasSuffix(name, ".yaml") || strings.HasSuffix(name, ".yml"):
			skill, parseErr = parsePipelineFile(path)
		default:
			continue
		}

		if parseErr != nil {
			return nil, fmt.Errorf("failed to parse skill %s: %w", name, parseErr)
		}
		if skill != nil {
			loaded = append(loaded, *skill)
		}
	}

	return loaded, nil
}

// parseSkillFile reads a Markdown file with optional YAML frontmatter.
func parseSkillFile(path string) (*Skill, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	content := string(data)
	skill := &Skill{FilePath: path}

	if strings.HasPrefix(content, "---") {
		parts := strings.SplitN(content[3:], "---", 2)
		if len(parts) == 2 {
			if err := yaml.Unmarshal([]byte(strings.TrimSpace(parts[0])), skill); err != nil {
				return nil, fmt.Errorf("invalid frontmatter YAML: %w", err)
			}
			skill.Prompt = strings.TrimSpace(parts[1])
		} else {
			skill.Prompt = content
		}
	} else {
		skill.Prompt = content
	}

	if skill.Name == "" {
		skill.Name = strings.TrimSuffix(filepath.Base(path), ".md")
	}
	// Merge legacy complexity field into Tier for backward compat.
	if skill.Tier == "" && skill.LegacyTier != "" {
		skill.Tier = skill.LegacyTier
	}
	return skill, nil
}

// parsePipelineFile reads a standalone YAML pipeline definition.
// The file must contain top-level fields: name, description, vars, pipeline.
func parsePipelineFile(path string) (*Skill, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	// The top-level YAML structure combines Skill metadata with PipelineSkill data.
	var raw struct {
		Name          string                 `yaml:"name"`
		Version       string                 `yaml:"version"`
		Description   string                 `yaml:"description"`
		Tier          string                 `yaml:"tier"`
		Complexity    string                 `yaml:"complexity"` // legacy alias
		AutoGenerated bool                   `yaml:"auto_generated"`
		SuccessCount  int                    `yaml:"success_count"`
		Returns       string                 `yaml:"returns"`
		Vars          map[string]interface{} `yaml:"vars"`
		Pipeline      []PipelineNode         `yaml:"pipeline"`
	}
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("invalid pipeline YAML: %w", err)
	}

	// Detect "pipeline:" key present but empty vs. file has no pipeline key.
	var keys map[string]interface{}
	if err := yaml.Unmarshal(data, &keys); err == nil {
		if _, hasPipeline := keys["pipeline"]; hasPipeline && len(raw.Pipeline) == 0 {
			return nil, fmt.Errorf("pipeline key is present but the node list is empty in %s", filepath.Base(path))
		}
	}

	// A YAML file without a pipeline key is not a pipeline skill — skip it silently.
	if len(raw.Pipeline) == 0 {
		return nil, nil
	}

	name := raw.Name
	if name == "" {
		base := filepath.Base(path)
		name = strings.TrimSuffix(strings.TrimSuffix(base, ".yml"), ".yaml")
	}

	if raw.Vars == nil {
		raw.Vars = make(map[string]interface{})
	}
	// Normalize primitive scalars to strings so downstream interpolation is type-safe.
	// Maps and slices are left as-is for JSON encoding by fmtVar.
	for k, v := range raw.Vars {
		switch val := v.(type) {
		case nil:
			raw.Vars[k] = ""
		case string:
			// already correct
		case int, int64, float64, bool:
			raw.Vars[k] = fmt.Sprintf("%v", val)
		}
	}
	// Ensure $vars.input always exists (populated from the user's message).
	if _, ok := raw.Vars["input"]; !ok {
		raw.Vars["input"] = ""
	}

	// Validate nodes.
	seenIDs := make(map[string]bool, len(raw.Pipeline))
	for i, node := range raw.Pipeline {
		if node.ID == "" {
			return nil, fmt.Errorf("node %d has no id", i)
		}
		if seenIDs[node.ID] {
			return nil, fmt.Errorf("duplicate node id %q", node.ID)
		}
		seenIDs[node.ID] = true
		if node.Type == "auto" && node.Tool == "" {
			return nil, fmt.Errorf("node %q has type=auto but no tool specified", node.ID)
		}
	}

	tier := raw.Tier
	if tier == "" {
		tier = raw.Complexity // backward compat
	}
	return &Skill{
		Name:          name,
		Version:       raw.Version,
		Description:   raw.Description,
		Tier:          tier,
		AutoGenerated: raw.AutoGenerated,
		SuccessCount:  raw.SuccessCount,
		FilePath:      path,
		Pipeline: &PipelineSkill{
			Returns:  raw.Returns,
			Vars:     raw.Vars,
			Pipeline: raw.Pipeline,
		},
	}, nil
}

// UpdateSkillSuccessCount reads filePath, updates success_count, and writes back.
// increment=true adds 1; increment=false resets to 0.
// Works for both .md (YAML frontmatter) and .yaml/.yml pipeline files.
func UpdateSkillSuccessCount(filePath string, increment bool) error {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return fmt.Errorf("read skill file: %w", err)
	}
	content := string(data)
	ext := strings.ToLower(filepath.Ext(filePath))

	if ext == ".md" {
		if !strings.HasPrefix(content, "---") {
			return nil // no frontmatter to update
		}
		rest := content[3:]
		parts := strings.SplitN(rest, "---", 2)
		if len(parts) < 2 {
			return nil
		}
		var s Skill
		if err := yaml.Unmarshal([]byte(strings.TrimSpace(parts[0])), &s); err != nil {
			return fmt.Errorf("parse frontmatter: %w", err)
		}
		newCount := 0
		if increment {
			newCount = s.SuccessCount + 1
		}
		newFront := setCountInYAMLText(strings.TrimSpace(parts[0]), newCount)
		newContent := "---\n" + newFront + "\n---" + parts[1]
		return os.WriteFile(filePath, []byte(newContent), 0o644)
	}

	// .yaml / .yml
	var s Skill
	if err := yaml.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("parse pipeline YAML: %w", err)
	}
	newCount := 0
	if increment {
		newCount = s.SuccessCount + 1
	}
	newContent := setCountInYAMLText(content, newCount)
	return os.WriteFile(filePath, []byte(newContent), 0o644)
}

// setCountInYAMLText updates or inserts the success_count field in a block of
// YAML text, preserving all other content.
func setCountInYAMLText(text string, newCount int) string {
	target := fmt.Sprintf("success_count: %d", newCount)
	lines := strings.Split(text, "\n")
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "success_count:") {
			lines[i] = target
			return strings.Join(lines, "\n")
		}
	}
	// Field absent — insert after auto_generated if present, else after the first line.
	insertAfter := 0
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "auto_generated:") {
			insertAfter = i
			break
		}
	}
	out := make([]string, 0, len(lines)+1)
	out = append(out, lines[:insertAfter+1]...)
	out = append(out, target)
	out = append(out, lines[insertAfter+1:]...)
	return strings.Join(out, "\n")
}

// LoadSkillByPath loads a single skill from an absolute file path.
// The file type is inferred from the extension (.md vs .yaml/.yml).
func LoadSkillByPath(path string) (*Skill, error) {
	name := filepath.Base(path)
	switch {
	case strings.HasSuffix(name, ".md"):
		return parseSkillFile(path)
	case strings.HasSuffix(name, ".yaml"), strings.HasSuffix(name, ".yml"):
		return parsePipelineFile(path)
	default:
		return nil, fmt.Errorf("unsupported skill file type: %s", filepath.Ext(path))
	}
}

// ── Utilities ─────────────────────────────────────────────────────────────────

// SkillsSummary returns a concise summary string of all skills for system prompts.
func SkillsSummary(all []Skill) string {
	if len(all) == 0 {
		return "No skills loaded."
	}

	var sb strings.Builder
	sb.WriteString("Available Skills:\n")
	for _, s := range all {
		fmt.Fprintf(&sb, "- **%s**", s.Name)
		if s.Description != "" {
			fmt.Fprintf(&sb, ": %s", s.Description)
		}
		if s.IsPipeline() {
			sb.WriteString(" [pipeline]")
		} else if len(s.RequiredTools) > 0 {
			fmt.Fprintf(&sb, " (tools: %s)", strings.Join(s.RequiredTools, ", "))
		}
		sb.WriteString("\n")
	}
	return sb.String()
}
